### ISSUE TITLE
Compile in Java 8

### ISSUE THREAD

**Issue by RicardoPoleo** [carlanton/mpd-tools#1]
Hello guys.

It is possible to compile the project in Java 8? The Project where we are working is based on Java 8 and upgrading to Java 10 is off the table and we would love to use your library.

Thanks in advance!

**Comment by carlanton** [comment]
Hi,

You could use version 0.6 of this library, which still works on java 8.

// Anton

**Comment by RicardoPoleo** [comment]
Amazing Anton!

I could compile just fine. 

Thanks!
