### ISSUE TITLE
NoClassDefFoundError when using objects

### ISSUE THREAD

**Issue by RicardoPoleo** [carlanton/mpd-tools#2]
When I try to use the library, I got this error

`java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/cfg/MapperBuilder`

I have been adding libraries as it has those errors has been appearing but, this one, I couldn't beat.

Any idea where I could get?

**Comment by jandersson-svt** [comment]
There are some minor issues due to java-versions etc. I guess you are using java11? I just forked it and I'm working on bumping it and some other minor things. Fixed the issues for me.

**Comment by RicardoPoleo** [comment]
Hello @jandersson-svt ,

In the end, the issue was that I wasn't adding the library in the other application that I'm building on (JMeter).

After adding the respective dependencies, it worked (with some issues as well that can be fixed)

I'm using, Java 8, version 0.6.

Anyways, I'm closing this issue, since this matter it been solved by the correct integration of the libraries.

Thanks, everyone!
